/**
 * Centralized Traditional Chinese UI copy (PRD §18.4 — 禁止將所有中文文字散落硬編碼在元件中).
 * Every user-facing string in the app should live here so future locales
 * (en / zh-CN / ja) only require adding sibling files, not touching
 * components.
 */
export const t = {
  appName: "Coach Note",
  tagline: "健身教練最快速的學員課表紀錄工具",

  common: {
    save: "儲存",
    cancel: "取消",
    delete: "刪除",
    edit: "編輯",
    back: "返回",
    confirm: "確認",
    add: "新增",
    search: "搜尋",
    loading: "載入中…",
    retry: "重新嘗試",
    close: "關閉",
    optional: "選填",
    required: "必填",
    unknownError: "發生錯誤，請稍後再試。",
    kg: "公斤",
    reps: "次",
  },

  nav: {
    home: "首頁",
    clients: "學員",
    training: "訓練",
    account: "我的",
  },

  home: {
    title: "今天",
    todaySessions: "今天的課",
    noSessionsToday: "今天還沒有課程紀錄。",
    resume: "繼續紀錄",
    open: "查看",
    weekSummary: "本週",
    weekSessions: (count: number) => `${count} 堂課`,
    weekClients: (count: number) => `${count} 位學員`,
    recentClients: "最近上課的學員",
    draft: "進行中",
  },

  account: {
    title: "我的",
    workspace: "工作區",
    email: "登入 Email",
    signOut: "登出",
  },

  trainingTab: {
    title: "訓練",
    subtitle: "點學員直接看他的訓練紀錄。",
    empty: "還沒有任何訓練紀錄。先幫學員建立一堂課吧。",
    neverTrained: "尚未上課",
  },

  training: {
    searchPlaceholder: "搜尋動作",
    noSearchResult: (term: string) => `找不到「${term}」，換個關鍵字或先在課程裡新增這個動作。`,
    filters: {
      all: "全部",
      chest: "胸",
      back: "背",
      legs: "腿",
      shoulders: "肩",
      arms: "手臂",
      core: "核心",
      other: "其他",
    },
    latestWeight: "最新重量",
    setCount: "組數",
    versusLast: "上次比較",
    setsUnit: (count: number) => `${count} 組`,
    same: "持平",
    firstTime: "首次",
    weekSummary: (count: number) => `本週 ${count} 個動作`,
    lastUpdated: (date: string) => `最近更新 ${date}`,
    daysAgo: (days: number) =>
      days === 0 ? "今天" : days === 1 ? "昨天" : `${days} 天前`,
    historyTitle: "歷史紀錄",
    latest: "最新",
    quickLogTitle: (name: string) => `新增「${name}」紀錄`,
    reuseLast: "沿用上次",
    reuseLastDetail: (weight: number, unit: string, sets: number) =>
      `上次：${weight} ${unit} × ${sets} 組`,
    weightLabel: "重量",
    setCountLabel: "組數",
    dateLabel: "日期",
    saved: "已新增紀錄",
    invalidInput: "重量填 0–9999、組數填 1–20，日期不能是未來。",
    openSession: "查看這堂課",
  },

  auth: {
    loginTitle: "登入",
    signupTitle: "註冊帳號",
    forgotPasswordTitle: "忘記密碼",
    email: "Email",
    password: "密碼",
    confirmPassword: "確認密碼",
    loginButton: "登入",
    signupButton: "註冊",
    logoutButton: "登出",
    goToSignup: "還沒有帳號？註冊",
    goToLogin: "已經有帳號？登入",
    forgotPasswordLink: "忘記密碼？",
    sendResetLink: "寄送重設密碼連結",
    resetLinkSent: "重設密碼連結已寄出，請至信箱查收。",
    backToLogin: "返回登入",
    invalidCredentials: "Email 或密碼錯誤，請再試一次。",
    signupSuccessCheckEmail: "註冊成功，請至信箱完成驗證後登入。",
    passwordMismatch: "兩次輸入的密碼不一致。",
    settingUpWorkspace: "正在建立您的教練工作空間…",
    checkingResetLink: "正在確認連結…",
    resetLinkInvalid: "這個重設連結無效或已經過期。",
    resetLinkInvalidHint:
      "重設連結只能使用一次，而且必須在申請的同一個瀏覽器開啟。請重新申請一次，並在收到信的同一台裝置上點開連結。",
    requestNewResetLink: "重新申請重設連結",
  },

  clients: {
    listTitle: "學員列表",
    searchPlaceholder: "搜尋學員姓名或暱稱",
    addClient: "新增學員",
    empty: "還沒有學員，新增第一位學員開始記錄。",
    archived: "已封存",
    showArchived: "顯示已封存學員",
    hideArchived: "隱藏已封存學員",
    lastSession: "最後上課",
    neverTrained: "尚未上過課",
    sessionCount: (count: number) => `累積 ${count} 堂課`,
    editClient: "編輯學員",
    newClientTitle: "新增學員",
    editClientTitle: "編輯學員",
    fullName: "姓名",
    nickname: "暱稱",
    gender: "性別",
    genderMale: "男",
    genderFemale: "女",
    genderOther: "其他",
    genderUnset: "不透露",
    birthDate: "出生日期",
    phone: "手機",
    email: "Email",
    heightCm: "身高（公分）",
    weightKg: "體重（公斤）",
    note: "備註",
    saveClient: "儲存學員資料",
    archiveClient: "封存學員",
    unarchiveClient: "取消封存",
    archiveConfirm: "封存後，此學員將從預設列表隱藏，訓練紀錄仍會保留。確定要封存嗎？",
    fullNameRequired: "請輸入姓名",
    startTodaySession: "安排課程",
    clientDetailTitle: "學員詳情",
    historyTitle: "歷史課程",
    noHistory: "尚無訓練紀錄。",
    viewHistory: "查看歷史課程",
    performanceTitle: "訓練紀錄",
    noPerformance: "尚無動作紀錄，完成第一堂課程後會顯示在這裡。",
    performanceLastDate: "最近一次",
  },

  workout: {
    todaySession: "今天課程",
    sessionDate: "課程日期",
    sessionTime: "課程時間",
    sessionDuration: "已進行時長",
    stopwatchStart: "開始",
    stopwatchPause: "暫停",
    stopwatchStop: "結束",
    addExercise: "新增動作",
    completeSession: "完成課程",
    noExercisesYet: "點擊下方按鈕新增第一個訓練動作。",
    addSet: "新增一組",
    deleteSet: "刪除",
    setNumber: (n: number) => `第 ${n} 組`,
    weight: "重量",
    reps: "次數",
    markComplete: "完成",
    markIncomplete: "取消完成",
    completeConfirmEmpty: "目前尚未加入任何動作，是否仍要完成課程？",
    completeConfirmTitle: "完成課程",
    sessionCompleted: "課程已完成",
    deleteExercise: "移除動作",
    deleteExerciseConfirm: "確定要移除這個動作嗎？已記錄的組數也會一併移除。",
    deleteSessionConfirm: "確定要刪除這堂課程紀錄嗎？此動作無法復原。",
    deleteSessionAction: "刪除這堂課程",
    doneEditing: "完成編輯",
    savingIndicator: "已自動儲存",
    saveFailed: "儲存失敗，請檢查網路後重試。",
    draft: "進行中",
    completed: "已完成",
    cancelled: "已取消",
    status: "課程狀態",
    exercisesCount: (n: number) => `${n} 個動作`,
    setsCount: (n: number) => `${n} 組`,
    coach: "教練",
    sessionNote: "課程備註",
  },

  exercisePicker: {
    title: "選擇訓練動作",
    searchPlaceholder: "搜尋動作名稱、分類、肌群、器材或標籤",
    recentUsed: "最近使用",
    byMuscleGroup: "依肌群瀏覽",
    allMuscleGroups: "全部",
    noResults: "找不到符合的動作。",
    createCustom: "建立自訂動作",
    createCustomTitle: "新增自訂動作",
    exerciseNameZh: "中文名稱",
    exerciseNameEn: "英文名稱",
    category: "動作分類",
    primaryMuscleGroup: "主要肌群",
    equipmentType: "使用器材",
    createAndAdd: "建立並加入課程",
    exerciseNameRequired: "請輸入動作名稱",
    tags: "標籤",
    editTags: "編輯標籤",
    createTag: "新增自訂標籤",
    newTagPlaceholder: "例如：肌肥大",
  },

  quickWeights: [-2.5, 2.5] as const,
  quickReps: [5, 6, 8, 10, 12, 15, 20] as const,

  states: {
    loading: "載入中…",
    error: "發生錯誤",
    errorGeneric: "無法載入資料，請稍後再試。",
    offlineNotice: "網路連線不穩定，資料將於恢復連線後自動同步。",
  },
} as const;
