-- Coach Note V1 seed data.
-- Reference data (categories/muscle groups/equipment) + ~60 system exercises
-- so a coach can actually use the app meaningfully on day one.
-- Applied automatically by `supabase db reset --local`.

begin;

-- ---------------------------------------------------------------------------
-- exercise_categories (PRD §7.4)
-- ---------------------------------------------------------------------------
insert into public.exercise_categories (code, name_zh_tw, name_en, sort_order) values
  ('chest', '胸部', 'Chest', 1),
  ('back', '背部', 'Back', 2),
  ('shoulders', '肩部', 'Shoulders', 3),
  ('legs', '腿部', 'Legs', 4),
  ('glutes', '臀部', 'Glutes', 5),
  ('biceps', '二頭肌', 'Biceps', 6),
  ('triceps', '三頭肌', 'Triceps', 7),
  ('core', '核心', 'Core', 8),
  ('cardio', '有氧', 'Cardio', 9),
  ('full_body', '全身', 'Full Body', 10),
  ('stretching', '伸展', 'Stretching', 11),
  ('other', '其他', 'Other', 12);

-- ---------------------------------------------------------------------------
-- muscle_groups (PRD §10.6, with parent/child examples)
-- ---------------------------------------------------------------------------
insert into public.muscle_groups (code, name_zh_tw, name_en, parent_id, sort_order) values
  ('chest', '胸部', 'Chest', null, 1),
  ('back', '背部', 'Back', null, 2),
  ('shoulders', '肩部', 'Shoulders', null, 3),
  ('legs', '腿部', 'Legs', null, 4),
  ('glutes', '臀部', 'Glutes', null, 5),
  ('biceps', '二頭肌', 'Biceps', null, 6),
  ('triceps', '三頭肌', 'Triceps', null, 7),
  ('core', '核心', 'Core', null, 8),
  ('full_body', '全身', 'Full Body', null, 9);

insert into public.muscle_groups (code, name_zh_tw, name_en, parent_id, sort_order)
select 'quadriceps', '股四頭肌', 'Quadriceps', id, 1 from public.muscle_groups where code = 'legs'
union all
select 'hamstrings', '腿後肌', 'Hamstrings', id, 2 from public.muscle_groups where code = 'legs'
union all
select 'calves', '小腿', 'Calves', id, 3 from public.muscle_groups where code = 'legs'
union all
select 'lats', '背闊肌', 'Lats', id, 1 from public.muscle_groups where code = 'back'
union all
select 'traps', '斜方肌', 'Trapezius', id, 2 from public.muscle_groups where code = 'back';

-- ---------------------------------------------------------------------------
-- equipment_types (PRD §7.4)
-- ---------------------------------------------------------------------------
insert into public.equipment_types (code, name_zh_tw, name_en, sort_order) values
  ('bodyweight', '徒手', 'Bodyweight', 1),
  ('barbell', '槓鈴', 'Barbell', 2),
  ('dumbbell', '啞鈴', 'Dumbbell', 3),
  ('kettlebell', '壺鈴', 'Kettlebell', 4),
  ('machine', '固定式器材', 'Machine', 5),
  ('cable', '滑輪', 'Cable', 6),
  ('resistance_band', '彈力帶', 'Resistance Band', 7),
  ('trx', 'TRX', 'TRX', 8),
  ('cardio_machine', '有氧器材', 'Cardio Machine', 9),
  ('other', '其他', 'Other', 10);

-- ---------------------------------------------------------------------------
-- exercises: system exercises (organization_id = null, is_system = true)
-- ---------------------------------------------------------------------------
insert into public.exercises (
  organization_id, category_id, primary_muscle_group_id, equipment_type_id,
  name_zh_tw, name_en, tracking_type, default_unit, is_system, is_active
)
select
  null, cat.id, mg.id, eq.id,
  v.name_zh_tw, v.name_en, v.tracking_type, v.default_unit, true, true
from (values
  -- 胸部 chest
  ('chest', 'chest', 'barbell', '槓鈴臥推', 'Barbell Bench Press', 'weight_reps', 'kg'),
  ('chest', 'chest', 'dumbbell', '啞鈴臥推', 'Dumbbell Bench Press', 'weight_reps', 'kg'),
  ('chest', 'chest', 'dumbbell', '上斜啞鈴臥推', 'Incline Dumbbell Press', 'weight_reps', 'kg'),
  ('chest', 'chest', 'cable', '滑輪夾胸', 'Cable Fly', 'weight_reps', 'kg'),
  ('chest', 'chest', 'bodyweight', '伏地挺身', 'Push Up', 'bodyweight_reps', 'kg'),
  ('chest', 'chest', 'machine', '坐姿胸推機', 'Chest Press Machine', 'weight_reps', 'kg'),
  ('chest', 'chest', 'bodyweight', '雙槓臂屈伸', 'Dips', 'bodyweight_reps', 'kg'),
  -- 背部 back
  ('back', 'back', 'barbell', '硬舉', 'Deadlift', 'weight_reps', 'kg'),
  ('back', 'lats', 'barbell', '槓鈴划船', 'Barbell Row', 'weight_reps', 'kg'),
  ('back', 'lats', 'cable', '滑輪下拉', 'Lat Pulldown', 'weight_reps', 'kg'),
  ('back', 'lats', 'bodyweight', '引體向上', 'Pull Up', 'bodyweight_reps', 'kg'),
  ('back', 'lats', 'cable', '坐姿划船', 'Seated Cable Row', 'weight_reps', 'kg'),
  ('back', 'lats', 'barbell', 'T槓划船', 'T-Bar Row', 'weight_reps', 'kg'),
  ('back', 'lats', 'dumbbell', '啞鈴單臂划船', 'Dumbbell Row', 'weight_reps', 'kg'),
  ('back', 'traps', 'cable', '臉拉', 'Face Pull', 'weight_reps', 'kg'),
  ('back', 'traps', 'barbell', '聳肩', 'Shrug', 'weight_reps', 'kg'),
  ('back', 'lats', 'trx', 'TRX划船', 'TRX Row', 'bodyweight_reps', 'kg'),
  -- 肩部 shoulders
  ('shoulders', 'shoulders', 'barbell', '站姿肩推', 'Overhead Press', 'weight_reps', 'kg'),
  ('shoulders', 'shoulders', 'dumbbell', '啞鈴肩推', 'Dumbbell Shoulder Press', 'weight_reps', 'kg'),
  ('shoulders', 'shoulders', 'dumbbell', '側平舉', 'Lateral Raise', 'weight_reps', 'kg'),
  ('shoulders', 'shoulders', 'dumbbell', '前平舉', 'Front Raise', 'weight_reps', 'kg'),
  ('shoulders', 'shoulders', 'dumbbell', '反向飛鳥', 'Rear Delt Fly', 'weight_reps', 'kg'),
  ('shoulders', 'shoulders', 'cable', '滑輪側平舉', 'Cable Lateral Raise', 'weight_reps', 'kg'),
  -- 腿部 legs
  ('legs', 'quadriceps', 'barbell', '槓鈴深蹲', 'Barbell Back Squat', 'weight_reps', 'kg'),
  ('legs', 'quadriceps', 'machine', '腿推機', 'Leg Press', 'weight_reps', 'kg'),
  ('legs', 'quadriceps', 'machine', '腿伸屈機', 'Leg Extension', 'weight_reps', 'kg'),
  ('legs', 'hamstrings', 'machine', '腿彎舉機', 'Leg Curl', 'weight_reps', 'kg'),
  ('legs', 'hamstrings', 'barbell', '羅馬尼亞硬舉', 'Romanian Deadlift', 'weight_reps', 'kg'),
  ('legs', 'quadriceps', 'dumbbell', '走動弓箭步', 'Walking Lunge', 'weight_reps', 'kg'),
  ('legs', 'quadriceps', 'dumbbell', '保加利亞分腿蹲', 'Bulgarian Split Squat', 'weight_reps', 'kg'),
  ('legs', 'calves', 'machine', '站姿提踵', 'Standing Calf Raise', 'weight_reps', 'kg'),
  ('legs', 'calves', 'machine', '坐姿提踵', 'Seated Calf Raise', 'weight_reps', 'kg'),
  ('legs', 'quadriceps', 'kettlebell', '高腳杯深蹲', 'Goblet Squat', 'weight_reps', 'kg'),
  -- 臀部 glutes
  ('glutes', 'glutes', 'barbell', '臀推', 'Hip Thrust', 'weight_reps', 'kg'),
  ('glutes', 'glutes', 'bodyweight', '橋式', 'Glute Bridge', 'bodyweight_reps', 'kg'),
  ('glutes', 'glutes', 'cable', '滑輪後踢腿', 'Cable Kickback', 'weight_reps', 'kg'),
  ('glutes', 'glutes', 'barbell', '相撲硬舉', 'Sumo Deadlift', 'weight_reps', 'kg'),
  -- 二頭肌 biceps
  ('biceps', 'biceps', 'barbell', '槓鈴彎舉', 'Barbell Curl', 'weight_reps', 'kg'),
  ('biceps', 'biceps', 'dumbbell', '啞鈴彎舉', 'Dumbbell Curl', 'weight_reps', 'kg'),
  ('biceps', 'biceps', 'dumbbell', '錘式彎舉', 'Hammer Curl', 'weight_reps', 'kg'),
  ('biceps', 'biceps', 'cable', '滑輪彎舉', 'Cable Curl', 'weight_reps', 'kg'),
  ('biceps', 'biceps', 'barbell', '牧師椅彎舉', 'Preacher Curl', 'weight_reps', 'kg'),
  -- 三頭肌 triceps
  ('triceps', 'triceps', 'cable', '三頭肌下壓', 'Triceps Pushdown', 'weight_reps', 'kg'),
  ('triceps', 'triceps', 'barbell', '臥推三頭肌伸展', 'Skull Crusher', 'weight_reps', 'kg'),
  ('triceps', 'triceps', 'dumbbell', '過頭三頭肌伸展', 'Overhead Triceps Extension', 'weight_reps', 'kg'),
  ('triceps', 'triceps', 'barbell', '窄握臥推', 'Close Grip Bench Press', 'weight_reps', 'kg'),
  -- 核心 core
  ('core', 'core', 'bodyweight', '平板支撐', 'Plank', 'duration', 'sec'),
  ('core', 'core', 'bodyweight', '捲腹', 'Crunch', 'bodyweight_reps', 'kg'),
  ('core', 'core', 'bodyweight', '懸吊抬腿', 'Hanging Leg Raise', 'bodyweight_reps', 'kg'),
  ('core', 'core', 'bodyweight', '俄羅斯轉體', 'Russian Twist', 'bodyweight_reps', 'kg'),
  ('core', 'core', 'cable', '滑輪捲腹', 'Cable Crunch', 'weight_reps', 'kg'),
  -- 有氧 cardio
  ('cardio', 'full_body', 'cardio_machine', '跑步機慢跑', 'Treadmill Run', 'duration', 'min'),
  ('cardio', 'full_body', 'cardio_machine', '飛輪腳踏車', 'Stationary Bike', 'duration', 'min'),
  ('cardio', 'full_body', 'cardio_machine', '划船機', 'Rowing Machine', 'duration', 'min'),
  ('cardio', 'full_body', 'bodyweight', '跳繩', 'Jump Rope', 'duration', 'min'),
  ('cardio', 'full_body', 'cardio_machine', '爬階機', 'Stair Climber', 'duration', 'min'),
  -- 全身 full body / other compound
  ('full_body', 'glutes', 'kettlebell', '壺鈴擺盪', 'Kettlebell Swing', 'weight_reps', 'kg'),
  ('full_body', 'full_body', 'bodyweight', '波比跳', 'Burpee', 'bodyweight_reps', 'kg'),
  ('full_body', 'full_body', 'barbell', '上膊挺舉', 'Clean and Press', 'weight_reps', 'kg'),
  ('full_body', 'full_body', 'other', '戰繩', 'Battle Rope', 'duration', 'sec')
) as v(category_code, muscle_code, equipment_code, name_zh_tw, name_en, tracking_type, default_unit)
join public.exercise_categories cat on cat.code = v.category_code
join public.muscle_groups mg on mg.code = v.muscle_code
join public.equipment_types eq on eq.code = v.equipment_code;
-- ---------------------------------------------------------------------------
-- exercises: expanded system exercise library (coach-provided master list,
-- 400 additional movements across warm-up, strength, core, conditioning,
-- TRX, bands, and mobility). Same insert pattern as above; `where not
-- exists` guards against double-seeding if this file is ever re-applied
-- against a database that already has these rows (e.g. re-running against
-- prod instead of only `db reset --local`).
-- ---------------------------------------------------------------------------
insert into public.exercises (
  organization_id, category_id, primary_muscle_group_id, equipment_type_id,
  name_zh_tw, name_en, tracking_type, default_unit, is_system, is_active
)
select
  null, cat.id, mg.id, eq.id,
  v.name_zh_tw, v.name_en, v.tracking_type, v.default_unit, true, true
from (values
  -- 熱身/活動度 Warm-up & Mobility
  ('stretching', 'full_body', 'bodyweight', '原地踏步', 'Marching', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '開合跳', 'Jumping Jack', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '高抬腿', 'High Knees', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '屁股踢', 'Butt Kicks', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '側向踏步', 'Lateral Step', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '熊爬', 'Bear Crawl', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '毛毛蟲爬行', 'Inchworm', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '世界最佳伸展', 'World''s Greatest Stretch', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '貓牛式', 'Cat-Cow', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '胸椎旋轉', 'Thoracic Rotation', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '穿針式', 'Thread the Needle', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '手臂畫圈', 'Arm Circles', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '肩胛繞環', 'Scapular Circles', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '肩關節控制旋轉', 'Shoulder CARs', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '髖關節控制旋轉', 'Hip CARs', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '髖部畫圈', 'Hip Circles', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '90/90 髖部伸展', '90/90 Hip Stretch', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '90/90 髖部轉換', '90/90 Hip Switch', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '髖屈肌動態伸展', 'Dynamic Hip Flexor Stretch', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '弓箭步轉體', 'Lunge with Rotation', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '側弓箭步伸展', 'Lateral Lunge Stretch', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '蛙式髖部伸展', 'Frog Stretch', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '深蹲活動度', 'Squat Mobility', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '深蹲停留', 'Deep Squat Hold', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '膝碰牆踝背屈', 'Knee-to-Wall Ankle Mobility', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '前後擺腿', 'Front-to-Back Leg Swing', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '左右擺腿', 'Lateral Leg Swing', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '腳踝畫圈', 'Ankle Circles', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '手腕活動', 'Wrist Mobility', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '頸部活動', 'Neck Mobility', 'bodyweight_reps', 'kg'),
  -- 深蹲類 Squat
  ('legs', 'quadriceps', 'bodyweight', '徒手深蹲', 'Bodyweight Squat', 'bodyweight_reps', 'kg'),
  ('legs', 'quadriceps', 'bodyweight', '箱式深蹲', 'Box Squat', 'bodyweight_reps', 'kg'),
  ('legs', 'quadriceps', 'dumbbell', '啞鈴深蹲', 'Dumbbell Squat', 'weight_reps', 'kg'),
  ('legs', 'quadriceps', 'kettlebell', '壺鈴深蹲', 'Kettlebell Squat', 'weight_reps', 'kg'),
  ('legs', 'quadriceps', 'bodyweight', '高槓深蹲', 'High-Bar Back Squat', 'bodyweight_reps', 'kg'),
  ('legs', 'quadriceps', 'bodyweight', '低槓深蹲', 'Low-Bar Back Squat', 'bodyweight_reps', 'kg'),
  ('legs', 'quadriceps', 'barbell', '槓鈴前蹲', 'Front Squat', 'weight_reps', 'kg'),
  ('legs', 'quadriceps', 'bodyweight', '澤奇深蹲', 'Zercher Squat', 'bodyweight_reps', 'kg'),
  ('legs', 'quadriceps', 'barbell', '安全槓深蹲', 'Safety Bar Squat', 'weight_reps', 'kg'),
  ('legs', 'quadriceps', 'barbell', '地雷管深蹲', 'Landmine Squat', 'weight_reps', 'kg'),
  ('legs', 'quadriceps', 'machine', '史密斯深蹲', 'Smith Machine Squat', 'weight_reps', 'kg'),
  ('legs', 'quadriceps', 'bodyweight', '哈克深蹲', 'Hack Squat', 'bodyweight_reps', 'kg'),
  ('legs', 'quadriceps', 'bodyweight', '腰帶深蹲', 'Belt Squat', 'bodyweight_reps', 'kg'),
  ('legs', 'quadriceps', 'bodyweight', '相撲深蹲', 'Sumo Squat', 'bodyweight_reps', 'kg'),
  ('legs', 'quadriceps', 'bodyweight', '窄距深蹲', 'Narrow-Stance Squat', 'bodyweight_reps', 'kg'),
  ('legs', 'quadriceps', 'bodyweight', '腳跟墊高深蹲', 'Heel-Elevated Squat', 'bodyweight_reps', 'kg'),
  ('legs', 'quadriceps', 'bodyweight', '西西深蹲', 'Sissy Squat', 'bodyweight_reps', 'kg'),
  ('legs', 'quadriceps', 'bodyweight', '跳躍深蹲', 'Jump Squat', 'bodyweight_reps', 'kg'),
  ('legs', 'quadriceps', 'bodyweight', '單腳箱式深蹲', 'Single-Leg Box Squat', 'bodyweight_reps', 'kg'),
  ('legs', 'quadriceps', 'bodyweight', '手槍深蹲', 'Pistol Squat', 'bodyweight_reps', 'kg'),
  ('legs', 'quadriceps', 'bodyweight', '蝦式深蹲', 'Shrimp Squat', 'bodyweight_reps', 'kg'),
  -- 弓箭步/分腿蹲 Lunge & Split Squat
  ('legs', 'quadriceps', 'bodyweight', '前弓箭步', 'Forward Lunge', 'bodyweight_reps', 'kg'),
  ('legs', 'quadriceps', 'bodyweight', '原地弓箭步', 'Stationary Lunge', 'bodyweight_reps', 'kg'),
  ('legs', 'quadriceps', 'bodyweight', '側弓箭步', 'Lateral Lunge', 'bodyweight_reps', 'kg'),
  ('legs', 'quadriceps', 'bodyweight', '交叉後弓箭步', 'Curtsy Lunge', 'bodyweight_reps', 'kg'),
  ('legs', 'quadriceps', 'bodyweight', '交叉弓箭步', 'Crossover Lunge', 'bodyweight_reps', 'kg'),
  ('legs', 'quadriceps', 'bodyweight', '分腿蹲', 'Split Squat', 'bodyweight_reps', 'kg'),
  ('legs', 'quadriceps', 'bodyweight', '前腳墊高分腿蹲', 'Front-Foot Elevated Split Squat', 'bodyweight_reps', 'kg'),
  ('legs', 'quadriceps', 'bodyweight', '後腳墊高分腿蹲', 'Rear-Foot Elevated Split Squat', 'bodyweight_reps', 'kg'),
  ('legs', 'quadriceps', 'bodyweight', '跳躍弓箭步', 'Jumping Lunge', 'bodyweight_reps', 'kg'),
  ('legs', 'quadriceps', 'dumbbell', '啞鈴弓箭步', 'Dumbbell Lunge', 'weight_reps', 'kg'),
  ('legs', 'quadriceps', 'barbell', '槓鈴弓箭步', 'Barbell Lunge', 'weight_reps', 'kg'),
  ('legs', 'quadriceps', 'kettlebell', '壺鈴弓箭步', 'Kettlebell Lunge', 'weight_reps', 'kg'),
  -- 硬舉/髖鉸鏈 Deadlift & Hip Hinge
  ('legs', 'hamstrings', 'bodyweight', '傳統硬舉', 'Conventional Deadlift', 'bodyweight_reps', 'kg'),
  ('legs', 'hamstrings', 'bodyweight', '直腿硬舉', 'Stiff-Leg Deadlift', 'bodyweight_reps', 'kg'),
  ('legs', 'hamstrings', 'barbell', '六角槓硬舉', 'Trap Bar Deadlift', 'weight_reps', 'kg'),
  ('legs', 'hamstrings', 'bodyweight', '架上硬舉', 'Rack Pull', 'bodyweight_reps', 'kg'),
  ('legs', 'hamstrings', 'bodyweight', '墊高硬舉', 'Block Pull', 'bodyweight_reps', 'kg'),
  ('legs', 'hamstrings', 'dumbbell', '啞鈴硬舉', 'Dumbbell Deadlift', 'weight_reps', 'kg'),
  ('legs', 'hamstrings', 'kettlebell', '壺鈴硬舉', 'Kettlebell Deadlift', 'weight_reps', 'kg'),
  ('legs', 'hamstrings', 'bodyweight', '單腳羅馬尼亞硬舉', 'Single-Leg Romanian Deadlift', 'bodyweight_reps', 'kg'),
  ('legs', 'hamstrings', 'bodyweight', 'B 站姿羅馬尼亞硬舉', 'B-Stance Romanian Deadlift', 'bodyweight_reps', 'kg'),
  ('legs', 'hamstrings', 'barbell', '地雷管羅馬尼亞硬舉', 'Landmine Romanian Deadlift', 'weight_reps', 'kg'),
  ('legs', 'hamstrings', 'bodyweight', '早安式', 'Good Morning', 'bodyweight_reps', 'kg'),
  ('legs', 'hamstrings', 'cable', '滑輪拉臀', 'Cable Pull-Through', 'weight_reps', 'kg'),
  ('legs', 'hamstrings', 'bodyweight', '單手壺鈴擺盪', 'One-Arm Kettlebell Swing', 'bodyweight_reps', 'kg'),
  ('legs', 'hamstrings', 'bodyweight', '雙壺鈴擺盪', 'Double Kettlebell Swing', 'bodyweight_reps', 'kg'),
  -- 臀部 Glutes
  ('glutes', 'glutes', 'bodyweight', '單腳臀橋', 'Single-Leg Glute Bridge', 'bodyweight_reps', 'kg'),
  ('glutes', 'glutes', 'dumbbell', '啞鈴臀推', 'Dumbbell Hip Thrust', 'weight_reps', 'kg'),
  ('glutes', 'glutes', 'bodyweight', '單腳臀推', 'Single-Leg Hip Thrust', 'bodyweight_reps', 'kg'),
  ('glutes', 'glutes', 'machine', '史密斯臀推', 'Smith Machine Hip Thrust', 'weight_reps', 'kg'),
  ('glutes', 'glutes', 'bodyweight', '蛙式臀橋', 'Frog Pump', 'bodyweight_reps', 'kg'),
  ('glutes', 'glutes', 'bodyweight', '跪姿後踢', 'Donkey Kick', 'bodyweight_reps', 'kg'),
  ('glutes', 'glutes', 'bodyweight', '消防栓式抬腿', 'Fire Hydrant', 'bodyweight_reps', 'kg'),
  ('glutes', 'glutes', 'bodyweight', '蚌式開合', 'Clamshell', 'bodyweight_reps', 'kg'),
  ('glutes', 'glutes', 'bodyweight', '側躺髖外展', 'Side-Lying Hip Abduction', 'bodyweight_reps', 'kg'),
  ('glutes', 'glutes', 'resistance_band', '彈力帶側走', 'Lateral Band Walk', 'weight_reps', 'kg'),
  ('glutes', 'glutes', 'bodyweight', '怪獸走路', 'Monster Walk', 'bodyweight_reps', 'kg'),
  ('glutes', 'glutes', 'machine', '髖外展機', 'Hip Abduction Machine', 'weight_reps', 'kg'),
  ('glutes', 'glutes', 'machine', '髖內收機', 'Hip Adduction Machine', 'weight_reps', 'kg'),
  ('glutes', 'glutes', 'bodyweight', '站姿髖外展', 'Standing Hip Abduction', 'bodyweight_reps', 'kg'),
  ('glutes', 'glutes', 'cable', '滑輪髖外展', 'Cable Hip Abduction', 'weight_reps', 'kg'),
  -- 大腿/腿部器械 Legs
  ('legs', 'legs', 'bodyweight', '單腳腿推', 'Single-Leg Press', 'bodyweight_reps', 'kg'),
  ('legs', 'legs', 'bodyweight', '單腳腿伸展', 'Single-Leg Extension', 'bodyweight_reps', 'kg'),
  ('legs', 'legs', 'bodyweight', '坐姿腿彎舉', 'Seated Leg Curl', 'bodyweight_reps', 'kg'),
  ('legs', 'legs', 'bodyweight', '臥姿腿彎舉', 'Lying Leg Curl', 'bodyweight_reps', 'kg'),
  ('legs', 'legs', 'bodyweight', '站姿腿彎舉', 'Standing Leg Curl', 'bodyweight_reps', 'kg'),
  ('legs', 'legs', 'bodyweight', '單腳腿彎舉', 'Single-Leg Curl', 'bodyweight_reps', 'kg'),
  ('legs', 'legs', 'bodyweight', '北歐腿彎舉', 'Nordic Hamstring Curl', 'bodyweight_reps', 'kg'),
  ('legs', 'legs', 'bodyweight', '反向北歐腿彎舉', 'Reverse Nordic Curl', 'bodyweight_reps', 'kg'),
  ('legs', 'legs', 'bodyweight', 'GHD 腿後側彎舉', 'GHD Hamstring Curl', 'bodyweight_reps', 'kg'),
  ('legs', 'legs', 'bodyweight', '台階踏上', 'Step-Up', 'bodyweight_reps', 'kg'),
  ('legs', 'legs', 'bodyweight', '側向台階踏上', 'Lateral Step-Up', 'bodyweight_reps', 'kg'),
  ('legs', 'legs', 'bodyweight', '台階下踩', 'Step-Down', 'bodyweight_reps', 'kg'),
  ('legs', 'legs', 'bodyweight', '側向台階下踩', 'Lateral Step-Down', 'bodyweight_reps', 'kg'),
  -- 小腿 Calves
  ('legs', 'calves', 'bodyweight', '單腳提踵', 'Single-Leg Calf Raise', 'bodyweight_reps', 'kg'),
  ('legs', 'calves', 'bodyweight', '驢式提踵', 'Donkey Calf Raise', 'bodyweight_reps', 'kg'),
  ('legs', 'calves', 'bodyweight', '腿推機提踵', 'Leg Press Calf Raise', 'bodyweight_reps', 'kg'),
  ('legs', 'calves', 'machine', '史密斯提踵', 'Smith Machine Calf Raise', 'weight_reps', 'kg'),
  ('legs', 'calves', 'bodyweight', '脛前肌抬腳', 'Tibialis Raise', 'bodyweight_reps', 'kg'),
  -- 胸部 Chest (additions)
  ('chest', 'chest', 'bodyweight', '跪姿伏地挺身', 'Knee Push-Up', 'bodyweight_reps', 'kg'),
  ('chest', 'chest', 'bodyweight', '上斜伏地挺身', 'Incline Push-Up', 'bodyweight_reps', 'kg'),
  ('chest', 'chest', 'bodyweight', '下斜伏地挺身', 'Decline Push-Up', 'bodyweight_reps', 'kg'),
  ('chest', 'chest', 'bodyweight', '窄距伏地挺身', 'Close-Grip Push-Up', 'bodyweight_reps', 'kg'),
  ('chest', 'chest', 'bodyweight', '寬距伏地挺身', 'Wide Push-Up', 'bodyweight_reps', 'kg'),
  ('chest', 'chest', 'bodyweight', '鑽石伏地挺身', 'Diamond Push-Up', 'bodyweight_reps', 'kg'),
  ('chest', 'chest', 'bodyweight', '爆發伏地挺身', 'Plyometric Push-Up', 'bodyweight_reps', 'kg'),
  ('chest', 'chest', 'bodyweight', '拍手伏地挺身', 'Clap Push-Up', 'bodyweight_reps', 'kg'),
  ('chest', 'chest', 'trx', 'TRX 伏地挺身', 'TRX Push-Up', 'weight_reps', 'kg'),
  ('chest', 'chest', 'bodyweight', '上斜槓鈴臥推', 'Incline Barbell Bench Press', 'bodyweight_reps', 'kg'),
  ('chest', 'chest', 'bodyweight', '下斜槓鈴臥推', 'Decline Barbell Bench Press', 'bodyweight_reps', 'kg'),
  ('chest', 'chest', 'bodyweight', '下斜啞鈴臥推', 'Decline Dumbbell Bench Press', 'bodyweight_reps', 'kg'),
  ('chest', 'chest', 'machine', '史密斯臥推', 'Smith Machine Bench Press', 'weight_reps', 'kg'),
  ('chest', 'chest', 'dumbbell', '啞鈴地板臥推', 'Dumbbell Floor Press', 'weight_reps', 'kg'),
  ('chest', 'chest', 'barbell', '槓鈴地板臥推', 'Barbell Floor Press', 'weight_reps', 'kg'),
  ('chest', 'chest', 'machine', '單手機械胸推', 'Single-Arm Chest Press', 'weight_reps', 'kg'),
  ('chest', 'chest', 'cable', '滑輪胸推', 'Cable Chest Press', 'weight_reps', 'kg'),
  ('chest', 'chest', 'bodyweight', '單手滑輪胸推', 'Single-Arm Cable Chest Press', 'bodyweight_reps', 'kg'),
  ('chest', 'chest', 'barbell', '地雷管胸推', 'Landmine Chest Press', 'weight_reps', 'kg'),
  ('chest', 'chest', 'dumbbell', '啞鈴飛鳥', 'Dumbbell Fly', 'weight_reps', 'kg'),
  ('chest', 'chest', 'bodyweight', '上斜啞鈴飛鳥', 'Incline Dumbbell Fly', 'bodyweight_reps', 'kg'),
  ('chest', 'chest', 'bodyweight', '高位向下滑輪飛鳥', 'High-to-Low Cable Fly', 'bodyweight_reps', 'kg'),
  ('chest', 'chest', 'bodyweight', '低位向上滑輪飛鳥', 'Low-to-High Cable Fly', 'bodyweight_reps', 'kg'),
  ('chest', 'chest', 'machine', '蝴蝶機夾胸', 'Pec Deck Fly', 'weight_reps', 'kg'),
  ('chest', 'chest', 'bodyweight', '夾片胸推', 'Svend Press', 'bodyweight_reps', 'kg'),
  -- 背部垂直拉 Back Vertical Pull
  ('back', 'lats', 'bodyweight', '反手引體向上', 'Chin-Up', 'bodyweight_reps', 'kg'),
  ('back', 'lats', 'bodyweight', '中立握引體向上', 'Neutral-Grip Pull-Up', 'bodyweight_reps', 'kg'),
  ('back', 'lats', 'bodyweight', '寬握引體向上', 'Wide-Grip Pull-Up', 'bodyweight_reps', 'kg'),
  ('back', 'lats', 'bodyweight', '輔助引體向上', 'Assisted Pull-Up', 'bodyweight_reps', 'kg'),
  ('back', 'lats', 'bodyweight', '寬握高位下拉', 'Wide-Grip Lat Pulldown', 'bodyweight_reps', 'kg'),
  ('back', 'lats', 'bodyweight', '窄握高位下拉', 'Close-Grip Lat Pulldown', 'bodyweight_reps', 'kg'),
  ('back', 'lats', 'bodyweight', '反握高位下拉', 'Reverse-Grip Lat Pulldown', 'bodyweight_reps', 'kg'),
  ('back', 'lats', 'bodyweight', '中立握高位下拉', 'Neutral-Grip Lat Pulldown', 'bodyweight_reps', 'kg'),
  ('back', 'lats', 'bodyweight', '單手高位下拉', 'Single-Arm Lat Pulldown', 'bodyweight_reps', 'kg'),
  ('back', 'lats', 'bodyweight', '直臂下拉', 'Straight-Arm Pulldown', 'bodyweight_reps', 'kg'),
  -- 背部划船 Back Row
  ('back', 'lats', 'bodyweight', '潘德雷划船', 'Pendlay Row', 'bodyweight_reps', 'kg'),
  ('back', 'lats', 'bodyweight', '葉慈划船', 'Yates Row', 'bodyweight_reps', 'kg'),
  ('back', 'lats', 'bodyweight', '雙手啞鈴划船', 'Dumbbell Bent-Over Row', 'bodyweight_reps', 'kg'),
  ('back', 'lats', 'bodyweight', '胸靠啞鈴划船', 'Chest-Supported Dumbbell Row', 'bodyweight_reps', 'kg'),
  ('back', 'lats', 'bodyweight', '海豹划船', 'Seal Row', 'bodyweight_reps', 'kg'),
  ('back', 'lats', 'barbell', '地雷管划船', 'Landmine Row', 'weight_reps', 'kg'),
  ('back', 'lats', 'bodyweight', '單手滑輪划船', 'Single-Arm Cable Row', 'bodyweight_reps', 'kg'),
  ('back', 'lats', 'bodyweight', '反向划船', 'Inverted Row', 'bodyweight_reps', 'kg'),
  ('back', 'lats', 'machine', '機械划船', 'Machine Row', 'weight_reps', 'kg'),
  ('back', 'lats', 'machine', '漢默機械划船', 'Hammer Strength Row', 'weight_reps', 'kg'),
  -- 上背/肩胛 Upper Back & Scapula
  ('back', 'traps', 'resistance_band', '彈力帶水平拉開', 'Band Pull-Apart', 'weight_reps', 'kg'),
  ('back', 'traps', 'machine', '反向蝴蝶機', 'Reverse Pec Deck', 'weight_reps', 'kg'),
  ('back', 'traps', 'cable', '滑輪反向飛鳥', 'Cable Reverse Fly', 'weight_reps', 'kg'),
  ('back', 'traps', 'bodyweight', '俯臥 Y 字抬舉', 'Prone Y Raise', 'bodyweight_reps', 'kg'),
  ('back', 'traps', 'bodyweight', '俯臥 T 字抬舉', 'Prone T Raise', 'bodyweight_reps', 'kg'),
  ('back', 'traps', 'bodyweight', '俯臥 W 字抬舉', 'Prone W Raise', 'bodyweight_reps', 'kg'),
  ('back', 'traps', 'bodyweight', '肩胛引體', 'Scapular Pull-Up', 'bodyweight_reps', 'kg'),
  ('back', 'traps', 'bodyweight', '肩胛划船', 'Scapular Row', 'bodyweight_reps', 'kg'),
  ('back', 'traps', 'bodyweight', '肩胛伏地挺身', 'Scapular Push-Up', 'bodyweight_reps', 'kg'),
  ('back', 'traps', 'bodyweight', '伏地挺身加強式', 'Push-Up Plus', 'bodyweight_reps', 'kg'),
  -- 肩膀 Shoulders (additions)
  ('shoulders', 'shoulders', 'bodyweight', '坐姿啞鈴肩推', 'Seated Dumbbell Shoulder Press', 'bodyweight_reps', 'kg'),
  ('shoulders', 'shoulders', 'bodyweight', '阿諾肩推', 'Arnold Press', 'bodyweight_reps', 'kg'),
  ('shoulders', 'shoulders', 'machine', '機械肩推', 'Machine Shoulder Press', 'weight_reps', 'kg'),
  ('shoulders', 'shoulders', 'machine', '史密斯肩推', 'Smith Machine Shoulder Press', 'weight_reps', 'kg'),
  ('shoulders', 'shoulders', 'barbell', '地雷管肩推', 'Landmine Press', 'weight_reps', 'kg'),
  ('shoulders', 'shoulders', 'bodyweight', '單手地雷管肩推', 'Single-Arm Landmine Press', 'bodyweight_reps', 'kg'),
  ('shoulders', 'shoulders', 'bodyweight', '借力肩推', 'Push Press', 'bodyweight_reps', 'kg'),
  ('shoulders', 'shoulders', 'bodyweight', 'Z 式肩推', 'Z Press', 'bodyweight_reps', 'kg'),
  ('shoulders', 'shoulders', 'machine', '機械側平舉', 'Machine Lateral Raise', 'weight_reps', 'kg'),
  ('shoulders', 'shoulders', 'bodyweight', '傾斜側平舉', 'Lean-Away Lateral Raise', 'bodyweight_reps', 'kg'),
  ('shoulders', 'shoulders', 'cable', '滑輪前平舉', 'Cable Front Raise', 'weight_reps', 'kg'),
  ('shoulders', 'shoulders', 'bodyweight', '槓片前平舉', 'Plate Front Raise', 'bodyweight_reps', 'kg'),
  ('shoulders', 'shoulders', 'cable', '滑輪後三角飛鳥', 'Cable Rear Delt Fly', 'weight_reps', 'kg'),
  ('shoulders', 'shoulders', 'bodyweight', '直立划船', 'Upright Row', 'bodyweight_reps', 'kg'),
  ('shoulders', 'shoulders', 'bodyweight', '古巴推舉', 'Cuban Press', 'bodyweight_reps', 'kg'),
  ('shoulders', 'shoulders', 'bodyweight', 'Y 字抬舉', 'Y Raise', 'bodyweight_reps', 'kg'),
  ('shoulders', 'shoulders', 'bodyweight', 'Lu Raise', 'Lu Raise', 'bodyweight_reps', 'kg'),
  -- 二頭肌 Biceps (additions)
  ('biceps', 'biceps', 'barbell', 'EZ 槓彎舉', 'EZ-Bar Curl', 'weight_reps', 'kg'),
  ('biceps', 'biceps', 'dumbbell', '啞鈴交替彎舉', 'Alternating Dumbbell Curl', 'weight_reps', 'kg'),
  ('biceps', 'biceps', 'bodyweight', '跨身錘式彎舉', 'Cross-Body Hammer Curl', 'bodyweight_reps', 'kg'),
  ('biceps', 'biceps', 'bodyweight', '上斜啞鈴彎舉', 'Incline Dumbbell Curl', 'bodyweight_reps', 'kg'),
  ('biceps', 'biceps', 'bodyweight', '集中彎舉', 'Concentration Curl', 'bodyweight_reps', 'kg'),
  ('biceps', 'biceps', 'bodyweight', '蜘蛛彎舉', 'Spider Curl', 'bodyweight_reps', 'kg'),
  ('biceps', 'biceps', 'bodyweight', '繩索錘式彎舉', 'Rope Hammer Curl', 'bodyweight_reps', 'kg'),
  ('biceps', 'biceps', 'bodyweight', '貝氏彎舉', 'Bayesian Curl', 'bodyweight_reps', 'kg'),
  ('biceps', 'biceps', 'machine', '機械二頭彎舉', 'Machine Biceps Curl', 'weight_reps', 'kg'),
  ('biceps', 'biceps', 'bodyweight', '反握彎舉', 'Reverse Curl', 'bodyweight_reps', 'kg'),
  ('biceps', 'biceps', 'bodyweight', '佐特曼彎舉', 'Zottman Curl', 'bodyweight_reps', 'kg'),
  ('biceps', 'biceps', 'bodyweight', '拖拉式彎舉', 'Drag Curl', 'bodyweight_reps', 'kg'),
  -- 三頭肌 Triceps (additions)
  ('triceps', 'triceps', 'bodyweight', '繩索下壓', 'Rope Pushdown', 'bodyweight_reps', 'kg'),
  ('triceps', 'triceps', 'bodyweight', '直桿下壓', 'Straight-Bar Pushdown', 'bodyweight_reps', 'kg'),
  ('triceps', 'triceps', 'bodyweight', '反握下壓', 'Reverse-Grip Pushdown', 'bodyweight_reps', 'kg'),
  ('triceps', 'triceps', 'dumbbell', '啞鈴過頭三頭伸展', 'Dumbbell Overhead Triceps Extension', 'weight_reps', 'kg'),
  ('triceps', 'triceps', 'bodyweight', '單手過頭三頭伸展', 'Single-Arm Overhead Triceps Extension', 'bodyweight_reps', 'kg'),
  ('triceps', 'triceps', 'barbell', 'EZ 槓仰臥三頭伸展', 'EZ-Bar Skull Crusher', 'weight_reps', 'kg'),
  ('triceps', 'triceps', 'bodyweight', '法式推舉', 'French Press', 'bodyweight_reps', 'kg'),
  ('triceps', 'triceps', 'dumbbell', '啞鈴三頭後踢', 'Dumbbell Triceps Kickback', 'weight_reps', 'kg'),
  ('triceps', 'triceps', 'cable', '滑輪三頭後踢', 'Cable Triceps Kickback', 'weight_reps', 'kg'),
  ('triceps', 'triceps', 'bodyweight', '長凳撐體', 'Bench Dip', 'bodyweight_reps', 'kg'),
  -- 核心撐體 Core Holds
  ('core', 'core', 'bodyweight', '高平板撐', 'High Plank', 'duration', 'sec'),
  ('core', 'core', 'bodyweight', 'RKC 平板撐', 'RKC Plank', 'duration', 'sec'),
  ('core', 'core', 'bodyweight', '身體鋸', 'Body Saw', 'duration', 'sec'),
  -- 核心 Core (additions)
  ('core', 'core', 'bodyweight', '健腹輪', 'Ab Wheel Rollout', 'bodyweight_reps', 'kg'),
  ('core', 'core', 'bodyweight', '瑞士球滾出', 'Stability Ball Rollout', 'bodyweight_reps', 'kg'),
  ('core', 'core', 'bodyweight', '死蟲式', 'Dead Bug', 'bodyweight_reps', 'kg'),
  -- 核心撐體 Core Holds
  ('core', 'core', 'bodyweight', '船式停留', 'Hollow Hold', 'duration', 'sec'),
  -- 核心 Core (additions)
  ('core', 'core', 'bodyweight', '船式擺動', 'Hollow Rock', 'bodyweight_reps', 'kg'),
  ('core', 'core', 'bodyweight', '帕洛夫推', 'Pallof Press', 'bodyweight_reps', 'kg'),
  -- 核心撐體 Core Holds
  ('core', 'core', 'bodyweight', '帕洛夫停留', 'Pallof Hold', 'duration', 'sec'),
  -- 核心 Core (additions)
  ('core', 'core', 'bodyweight', '高跪姿帕洛夫推', 'Tall-Kneeling Pallof Press', 'bodyweight_reps', 'kg'),
  ('core', 'core', 'bodyweight', '半跪姿帕洛夫推', 'Half-Kneeling Pallof Press', 'bodyweight_reps', 'kg'),
  ('core', 'core', 'bodyweight', '鳥狗式', 'Bird Dog', 'bodyweight_reps', 'kg'),
  ('core', 'core', 'bodyweight', '鳥狗划船', 'Bird Dog Row', 'bodyweight_reps', 'kg'),
  -- 核心撐體 Core Holds
  ('core', 'core', 'bodyweight', '側平板撐', 'Side Plank', 'duration', 'sec'),
  ('core', 'core', 'bodyweight', '哥本哈根側平板', 'Copenhagen Plank', 'duration', 'sec'),
  -- 功能性訓練 Functional Training
  ('core', 'core', 'bodyweight', '單側行走', 'Suitcase Carry', 'bodyweight_reps', 'kg'),
  ('core', 'core', 'bodyweight', '偏重農夫走路', 'Offset Farmer Carry', 'bodyweight_reps', 'kg'),
  -- 核心 Core (additions)
  ('core', 'core', 'machine', '機械捲腹', 'Machine Crunch', 'weight_reps', 'kg'),
  ('core', 'core', 'bodyweight', '反向捲腹', 'Reverse Crunch', 'bodyweight_reps', 'kg'),
  ('core', 'core', 'cardio_machine', '自行車捲腹', 'Bicycle Crunch', 'weight_reps', 'kg'),
  ('core', 'core', 'bodyweight', 'V 字起身', 'V-Up', 'bodyweight_reps', 'kg'),
  ('core', 'core', 'bodyweight', '仰臥起坐', 'Sit-Up', 'bodyweight_reps', 'kg'),
  ('core', 'core', 'bodyweight', '下斜仰臥起坐', 'Decline Sit-Up', 'bodyweight_reps', 'kg'),
  ('core', 'core', 'bodyweight', '摸腳尖捲腹', 'Toe Touch', 'bodyweight_reps', 'kg'),
  ('core', 'core', 'bodyweight', '折刀式', 'Jackknife', 'bodyweight_reps', 'kg'),
  ('core', 'core', 'bodyweight', '仰臥抬腿', 'Lying Leg Raise', 'bodyweight_reps', 'kg'),
  ('core', 'core', 'bodyweight', '懸垂屈膝', 'Hanging Knee Raise', 'bodyweight_reps', 'kg'),
  ('core', 'core', 'bodyweight', '羅馬椅屈膝', 'Captain''s Chair Knee Raise', 'bodyweight_reps', 'kg'),
  ('core', 'core', 'bodyweight', '腳碰槓', 'Toes-to-Bar', 'bodyweight_reps', 'kg'),
  ('core', 'core', 'cable', '滑輪伐木', 'Cable Wood Chop', 'weight_reps', 'kg'),
  ('core', 'core', 'bodyweight', '高至低伐木', 'High-to-Low Cable Chop', 'bodyweight_reps', 'kg'),
  ('core', 'core', 'bodyweight', '低至高伐木', 'Low-to-High Cable Chop', 'bodyweight_reps', 'kg'),
  ('core', 'core', 'barbell', '地雷管旋轉', 'Landmine Rotation', 'weight_reps', 'kg'),
  ('core', 'core', 'other', '藥球旋轉', 'Medicine Ball Rotation', 'weight_reps', 'kg'),
  -- 功能性訓練 Functional Training
  ('full_body', 'full_body', 'bodyweight', '農夫走路', 'Farmer''s Walk', 'bodyweight_reps', 'kg'),
  ('full_body', 'full_body', 'bodyweight', '前架負重行走', 'Front Rack Carry', 'bodyweight_reps', 'kg'),
  ('full_body', 'full_body', 'bodyweight', '過頭負重行走', 'Overhead Carry', 'bodyweight_reps', 'kg'),
  ('full_body', 'full_body', 'bodyweight', '侍者行走', 'Waiter''s Carry', 'bodyweight_reps', 'kg'),
  ('full_body', 'full_body', 'bodyweight', '熊抱負重行走', 'Bear Hug Carry', 'bodyweight_reps', 'kg'),
  ('full_body', 'full_body', 'other', '沙袋負重行走', 'Sandbag Carry', 'weight_reps', 'kg'),
  ('full_body', 'full_body', 'other', '雪橇推', 'Sled Push', 'weight_reps', 'kg'),
  ('full_body', 'full_body', 'other', '雪橇拉', 'Sled Pull', 'weight_reps', 'kg'),
  ('full_body', 'full_body', 'bodyweight', '繩索拉動', 'Rope Pull', 'bodyweight_reps', 'kg'),
  ('full_body', 'full_body', 'bodyweight', '戰繩雙手波浪', 'Battle Rope Waves', 'bodyweight_reps', 'kg'),
  ('full_body', 'full_body', 'bodyweight', '戰繩交替波浪', 'Alternating Battle Rope Waves', 'bodyweight_reps', 'kg'),
  ('full_body', 'full_body', 'bodyweight', '戰繩砸地', 'Battle Rope Slam', 'bodyweight_reps', 'kg'),
  ('full_body', 'full_body', 'other', '輪胎翻轉', 'Tire Flip', 'weight_reps', 'kg'),
  ('full_body', 'full_body', 'other', '輪胎拖行', 'Tire Drag', 'weight_reps', 'kg'),
  ('full_body', 'full_body', 'other', '沙袋翻舉', 'Sandbag Clean', 'weight_reps', 'kg'),
  ('full_body', 'full_body', 'other', '沙袋深蹲', 'Sandbag Squat', 'weight_reps', 'kg'),
  ('full_body', 'full_body', 'other', '沙袋上肩', 'Sandbag Shouldering', 'weight_reps', 'kg'),
  ('full_body', 'full_body', 'kettlebell', '壺鈴翻舉', 'Kettlebell Clean', 'weight_reps', 'kg'),
  ('full_body', 'full_body', 'kettlebell', '壺鈴抓舉', 'Kettlebell Snatch', 'weight_reps', 'kg'),
  ('full_body', 'full_body', 'kettlebell', '壺鈴翻舉肩推', 'Kettlebell Clean and Press', 'weight_reps', 'kg'),
  ('full_body', 'full_body', 'bodyweight', '土耳其起身', 'Turkish Get-Up', 'bodyweight_reps', 'kg'),
  ('full_body', 'full_body', 'dumbbell', '啞鈴推蹲', 'Dumbbell Thruster', 'weight_reps', 'kg'),
  ('full_body', 'full_body', 'barbell', '槓鈴推蹲', 'Barbell Thruster', 'weight_reps', 'kg'),
  ('full_body', 'full_body', 'bodyweight', '全能者動作', 'Man Maker', 'bodyweight_reps', 'kg'),
  ('full_body', 'full_body', 'bodyweight', '惡魔推舉', 'Devil Press', 'bodyweight_reps', 'kg'),
  ('full_body', 'full_body', 'bodyweight', '伏地啞鈴划船', 'Renegade Row', 'bodyweight_reps', 'kg'),
  ('full_body', 'full_body', 'bodyweight', '波比箱跳', 'Burpee Box Jump', 'bodyweight_reps', 'kg'),
  -- 爆發力 Plyometrics
  ('full_body', 'legs', 'bodyweight', '深蹲跳', 'Squat Jump', 'bodyweight_reps', 'kg'),
  ('full_body', 'legs', 'bodyweight', '反向動作跳', 'Countermovement Jump', 'bodyweight_reps', 'kg'),
  ('full_body', 'legs', 'bodyweight', '箱跳', 'Box Jump', 'bodyweight_reps', 'kg'),
  ('full_body', 'legs', 'bodyweight', '下箱跳', 'Step-Off Box Jump', 'bodyweight_reps', 'kg'),
  ('full_body', 'legs', 'bodyweight', '立定跳遠', 'Broad Jump', 'bodyweight_reps', 'kg'),
  ('full_body', 'legs', 'bodyweight', '單腳跳', 'Single-Leg Jump', 'bodyweight_reps', 'kg'),
  ('full_body', 'legs', 'bodyweight', '側向跨跳', 'Lateral Bound', 'bodyweight_reps', 'kg'),
  ('full_body', 'legs', 'bodyweight', '滑冰者跳', 'Skater Jump', 'bodyweight_reps', 'kg'),
  ('full_body', 'legs', 'bodyweight', '分腿跳', 'Split Jump', 'bodyweight_reps', 'kg'),
  ('full_body', 'legs', 'bodyweight', '深度跳', 'Depth Jump', 'bodyweight_reps', 'kg'),
  ('full_body', 'legs', 'bodyweight', '踝跳', 'Pogo Jump', 'bodyweight_reps', 'kg'),
  ('full_body', 'legs', 'bodyweight', '屈膝跳', 'Tuck Jump', 'bodyweight_reps', 'kg'),
  -- 藥球 Medicine Ball
  ('full_body', 'full_body', 'other', '藥球胸前投擲', 'Medicine Ball Chest Pass', 'weight_reps', 'kg'),
  ('full_body', 'full_body', 'other', '藥球砸地', 'Medicine Ball Slam', 'weight_reps', 'kg'),
  ('full_body', 'full_body', 'other', '藥球過頭投擲', 'Overhead Medicine Ball Throw', 'weight_reps', 'kg'),
  ('full_body', 'full_body', 'other', '藥球旋轉投擲', 'Rotational Medicine Ball Throw', 'weight_reps', 'kg'),
  ('full_body', 'full_body', 'other', '藥球鏟式投擲', 'Medicine Ball Scoop Toss', 'weight_reps', 'kg'),
  ('full_body', 'full_body', 'other', '藥球深蹲投擲', 'Medicine Ball Squat Throw', 'weight_reps', 'kg'),
  -- 敏捷/速度 Agility & Speed
  ('full_body', 'full_body', 'bodyweight', '短距離衝刺', 'Sprint', 'duration', 'sec'),
  ('full_body', 'full_body', 'bodyweight', '加速跑', 'Acceleration Sprint', 'duration', 'sec'),
  ('full_body', 'full_body', 'bodyweight', '折返跑', 'Shuttle Run', 'duration', 'sec'),
  ('full_body', 'full_body', 'bodyweight', '側向滑步', 'Lateral Shuffle', 'duration', 'sec'),
  ('full_body', 'full_body', 'bodyweight', '交叉跑', 'Carioca', 'duration', 'sec'),
  ('full_body', 'full_body', 'other', '標誌筒訓練', 'Cone Drill', 'duration', 'sec'),
  ('full_body', 'full_body', 'bodyweight', 'T 字敏捷跑', 'T-Drill', 'duration', 'sec'),
  ('full_body', 'full_body', 'bodyweight', '5-10-5 折返跑', '5-10-5 Shuttle', 'duration', 'sec'),
  ('full_body', 'full_body', 'bodyweight', '敏捷梯訓練', 'Agility Ladder Drill', 'duration', 'sec'),
  ('full_body', 'full_body', 'bodyweight', '快速腳步', 'Quick Feet', 'duration', 'sec'),
  ('full_body', 'full_body', 'bodyweight', '前後快速移動', 'Forward-Backward Shuffle', 'duration', 'sec'),
  ('full_body', 'full_body', 'bodyweight', '側向折返跑', 'Lateral Shuttle', 'duration', 'sec'),
  -- 奧林匹克舉重 Olympic Weightlifting
  ('full_body', 'full_body', 'bodyweight', '爆發翻舉', 'Power Clean', 'bodyweight_reps', 'kg'),
  ('full_body', 'full_body', 'bodyweight', '懸垂翻舉', 'Hang Clean', 'bodyweight_reps', 'kg'),
  ('full_body', 'full_body', 'bodyweight', '翻舉', 'Clean', 'bodyweight_reps', 'kg'),
  ('full_body', 'full_body', 'bodyweight', '翻舉拉', 'Clean Pull', 'bodyweight_reps', 'kg'),
  ('full_body', 'full_body', 'bodyweight', '高拉', 'High Pull', 'bodyweight_reps', 'kg'),
  ('full_body', 'full_body', 'bodyweight', '爆發抓舉', 'Power Snatch', 'bodyweight_reps', 'kg'),
  ('full_body', 'full_body', 'bodyweight', '懸垂抓舉', 'Hang Snatch', 'bodyweight_reps', 'kg'),
  ('full_body', 'full_body', 'bodyweight', '抓舉', 'Snatch', 'bodyweight_reps', 'kg'),
  ('full_body', 'full_body', 'bodyweight', '抓舉拉', 'Snatch Pull', 'bodyweight_reps', 'kg'),
  ('full_body', 'full_body', 'bodyweight', '借力挺舉', 'Push Jerk', 'bodyweight_reps', 'kg'),
  ('full_body', 'full_body', 'bodyweight', '分腿挺舉', 'Split Jerk', 'bodyweight_reps', 'kg'),
  ('full_body', 'full_body', 'bodyweight', '挺舉', 'Clean and Jerk', 'bodyweight_reps', 'kg'),
  ('full_body', 'full_body', 'bodyweight', '肌力翻舉', 'Muscle Clean', 'bodyweight_reps', 'kg'),
  ('full_body', 'full_body', 'bodyweight', '肌力抓舉', 'Muscle Snatch', 'bodyweight_reps', 'kg'),
  ('full_body', 'full_body', 'bodyweight', '過頭深蹲', 'Overhead Squat', 'bodyweight_reps', 'kg'),
  -- 有氧 Cardio (additions)
  ('cardio', 'full_body', 'bodyweight', '跑步', 'Running', 'duration', 'min'),
  ('cardio', 'full_body', 'bodyweight', '快走', 'Brisk Walking', 'duration', 'min'),
  ('cardio', 'full_body', 'cardio_machine', '坡度走路', 'Incline Walking', 'duration', 'min'),
  ('cardio', 'full_body', 'cardio_machine', '自行車', 'Cycling', 'duration', 'min'),
  ('cardio', 'full_body', 'machine', '滑雪機', 'SkiErg', 'duration', 'min'),
  ('cardio', 'full_body', 'machine', '橢圓機', 'Elliptical Trainer', 'duration', 'min'),
  ('cardio', 'full_body', 'cardio_machine', '風扇自行車', 'Air Bike', 'duration', 'min'),
  ('cardio', 'full_body', 'cardio_machine', '突擊自行車', 'Assault Bike', 'duration', 'min'),
  ('cardio', 'full_body', 'bodyweight', '雙迴旋跳繩', 'Double Under', 'duration', 'min'),
  ('cardio', 'full_body', 'bodyweight', '登山者', 'Mountain Climber', 'duration', 'min'),
  -- 平衡/單腳 Balance & Unilateral
  ('full_body', 'legs', 'bodyweight', '單腳站立', 'Single-Leg Balance', 'bodyweight_reps', 'kg'),
  ('full_body', 'legs', 'bodyweight', '閉眼單腳站立', 'Eyes-Closed Single-Leg Balance', 'bodyweight_reps', 'kg'),
  ('full_body', 'legs', 'bodyweight', '單腳觸地', 'Single-Leg Reach', 'bodyweight_reps', 'kg'),
  ('full_body', 'legs', 'bodyweight', '單腳深蹲', 'Single-Leg Squat', 'bodyweight_reps', 'kg'),
  ('full_body', 'legs', 'machine', 'BOSU 深蹲', 'BOSU Squat', 'weight_reps', 'kg'),
  ('full_body', 'legs', 'machine', 'BOSU 平衡', 'BOSU Balance', 'weight_reps', 'kg'),
  ('full_body', 'legs', 'other', '平衡墊單腳站立', 'Balance Pad Single-Leg Stand', 'weight_reps', 'kg'),
  ('full_body', 'legs', 'machine', '髖飛機', 'Hip Airplane', 'weight_reps', 'kg'),
  -- TRX 懸吊訓練 Suspension Training
  ('legs', 'quadriceps', 'trx', 'TRX 深蹲', 'TRX Squat', 'weight_reps', 'kg'),
  ('legs', 'quadriceps', 'trx', 'TRX 分腿蹲', 'TRX Split Squat', 'weight_reps', 'kg'),
  ('legs', 'quadriceps', 'trx', 'TRX 後弓箭步', 'TRX Reverse Lunge', 'weight_reps', 'kg'),
  ('legs', 'quadriceps', 'trx', 'TRX 單腳深蹲', 'TRX Single-Leg Squat', 'weight_reps', 'kg'),
  ('back', 'lats', 'trx', 'TRX 高位划船', 'TRX High Row', 'weight_reps', 'kg'),
  ('back', 'lats', 'trx', 'TRX 低位划船', 'TRX Low Row', 'weight_reps', 'kg'),
  ('back', 'traps', 'trx', 'TRX Y 字飛鳥', 'TRX Y Fly', 'weight_reps', 'kg'),
  ('back', 'traps', 'trx', 'TRX T 字飛鳥', 'TRX T Fly', 'weight_reps', 'kg'),
  ('chest', 'chest', 'trx', 'TRX 胸推', 'TRX Chest Press', 'weight_reps', 'kg'),
  ('triceps', 'triceps', 'trx', 'TRX 三頭伸展', 'TRX Triceps Extension', 'weight_reps', 'kg'),
  ('biceps', 'biceps', 'trx', 'TRX 二頭彎舉', 'TRX Biceps Curl', 'weight_reps', 'kg'),
  -- TRX 撐體 TRX Holds
  ('core', 'core', 'trx', 'TRX 平板撐', 'TRX Plank', 'duration', 'sec'),
  -- TRX 懸吊訓練 Suspension Training
  ('full_body', 'full_body', 'trx', 'TRX 屈膝', 'TRX Knee Tuck', 'weight_reps', 'kg'),
  ('full_body', 'full_body', 'trx', 'TRX 屈體', 'TRX Pike', 'weight_reps', 'kg'),
  ('full_body', 'full_body', 'trx', 'TRX 登山者', 'TRX Mountain Climber', 'weight_reps', 'kg'),
  ('legs', 'hamstrings', 'trx', 'TRX 腿彎舉', 'TRX Hamstring Curl', 'weight_reps', 'kg'),
  ('glutes', 'glutes', 'trx', 'TRX 臀推', 'TRX Hip Press', 'weight_reps', 'kg'),
  ('full_body', 'full_body', 'trx', 'TRX 前傾伸展', 'TRX Fallout', 'weight_reps', 'kg'),
  -- 彈力帶 Resistance Band
  ('legs', 'quadriceps', 'resistance_band', '彈力帶深蹲', 'Band Squat', 'weight_reps', 'kg'),
  ('legs', 'hamstrings', 'resistance_band', '彈力帶硬舉', 'Band Deadlift', 'weight_reps', 'kg'),
  ('legs', 'hamstrings', 'resistance_band', '彈力帶羅馬尼亞硬舉', 'Band Romanian Deadlift', 'weight_reps', 'kg'),
  ('legs', 'hamstrings', 'resistance_band', '彈力帶早安式', 'Band Good Morning', 'weight_reps', 'kg'),
  ('glutes', 'glutes', 'resistance_band', '彈力帶臀橋', 'Band Glute Bridge', 'weight_reps', 'kg'),
  ('glutes', 'glutes', 'resistance_band', '彈力帶臀推', 'Band Hip Thrust', 'weight_reps', 'kg'),
  ('glutes', 'glutes', 'resistance_band', '彈力帶髖外展', 'Band Hip Abduction', 'weight_reps', 'kg'),
  ('glutes', 'glutes', 'resistance_band', '彈力帶髖內收', 'Band Hip Adduction', 'weight_reps', 'kg'),
  ('glutes', 'glutes', 'resistance_band', '彈力帶後踢', 'Band Kickback', 'weight_reps', 'kg'),
  ('back', 'lats', 'resistance_band', '彈力帶划船', 'Band Row', 'weight_reps', 'kg'),
  ('back', 'lats', 'resistance_band', '彈力帶高位下拉', 'Band Lat Pulldown', 'weight_reps', 'kg'),
  ('back', 'traps', 'resistance_band', '彈力帶面拉', 'Band Face Pull', 'weight_reps', 'kg'),
  ('chest', 'chest', 'resistance_band', '彈力帶胸推', 'Band Chest Press', 'weight_reps', 'kg'),
  ('shoulders', 'shoulders', 'resistance_band', '彈力帶肩推', 'Band Shoulder Press', 'weight_reps', 'kg'),
  ('shoulders', 'shoulders', 'resistance_band', '彈力帶側平舉', 'Band Lateral Raise', 'weight_reps', 'kg'),
  ('biceps', 'biceps', 'resistance_band', '彈力帶二頭彎舉', 'Band Biceps Curl', 'weight_reps', 'kg'),
  ('triceps', 'triceps', 'resistance_band', '彈力帶三頭伸展', 'Band Triceps Extension', 'weight_reps', 'kg'),
  ('core', 'core', 'resistance_band', '彈力帶帕洛夫推', 'Band Pallof Press', 'weight_reps', 'kg'),
  -- 肩袖/肩膀穩定 Rotator Cuff & Shoulder Stability
  ('shoulders', 'shoulders', 'resistance_band', '彈力帶肩外旋', 'Band External Rotation', 'weight_reps', 'kg'),
  ('shoulders', 'shoulders', 'cable', '滑輪肩外旋', 'Cable External Rotation', 'weight_reps', 'kg'),
  ('shoulders', 'shoulders', 'resistance_band', '彈力帶肩內旋', 'Band Internal Rotation', 'weight_reps', 'kg'),
  ('shoulders', 'shoulders', 'cable', '滑輪肩內旋', 'Cable Internal Rotation', 'weight_reps', 'kg'),
  ('shoulders', 'shoulders', 'bodyweight', '側躺肩外旋', 'Side-Lying External Rotation', 'bodyweight_reps', 'kg'),
  ('shoulders', 'shoulders', 'bodyweight', '牆面滑手', 'Wall Slide', 'bodyweight_reps', 'kg'),
  ('shoulders', 'shoulders', 'bodyweight', '前鋸肌牆面滑手', 'Serratus Wall Slide', 'bodyweight_reps', 'kg'),
  ('shoulders', 'shoulders', 'bodyweight', 'Y-T-W 肩胛訓練', 'Y-T-W Exercise', 'bodyweight_reps', 'kg'),
  ('shoulders', 'shoulders', 'bodyweight', '牆天使', 'Wall Angel', 'bodyweight_reps', 'kg'),
  ('shoulders', 'shoulders', 'kettlebell', '壺鈴底朝上肩推', 'Bottom-Up Kettlebell Press', 'weight_reps', 'kg'),
  ('shoulders', 'shoulders', 'kettlebell', '壺鈴底朝上行走', 'Bottom-Up Kettlebell Carry', 'weight_reps', 'kg'),
  -- 收操/靜態伸展 Cool Down & Stretching
  ('stretching', 'full_body', 'bodyweight', '嬰兒式', 'Child''s Pose', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '眼鏡蛇式', 'Cobra Stretch', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '背闊肌伸展', 'Lat Stretch', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '胸肌伸展', 'Chest Stretch', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '門框胸肌伸展', 'Doorway Chest Stretch', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '橫跨手臂肩部伸展', 'Cross-Body Shoulder Stretch', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '三頭肌伸展', 'Triceps Stretch', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '上斜方肌伸展', 'Upper Trapezius Stretch', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '提肩胛肌伸展', 'Levator Scapulae Stretch', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '髖屈肌伸展', 'Hip Flexor Stretch', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '沙發伸展', 'Couch Stretch', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '股四頭肌伸展', 'Quadriceps Stretch', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '腿後肌伸展', 'Hamstring Stretch', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '四字臀部伸展', 'Figure-Four Stretch', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '梨狀肌伸展', 'Piriformis Stretch', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '臀肌伸展', 'Glute Stretch', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '內收肌伸展', 'Adductor Stretch', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '蛙式伸展', 'Frog Stretch (Cool Down)', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '小腿伸展', 'Calf Stretch', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '比目魚肌伸展', 'Soleus Stretch', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '鴿式', 'Pigeon Pose', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '仰臥脊椎扭轉', 'Supine Spinal Twist', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '呼吸訓練', 'Breathing Drill', 'bodyweight_reps', 'kg'),
  ('stretching', 'full_body', 'bodyweight', '90/90 呼吸', '90/90 Breathing', 'bodyweight_reps', 'kg')
) as v(category_code, muscle_code, equipment_code, name_zh_tw, name_en, tracking_type, default_unit)
join public.exercise_categories cat on cat.code = v.category_code
join public.muscle_groups mg on mg.code = v.muscle_code
join public.equipment_types eq on eq.code = v.equipment_code
where not exists (
  select 1 from public.exercises e
  where e.is_system = true and e.name_zh_tw = v.name_zh_tw
);

commit;
